### ISSUE TITLE
Smart Mute should only affect sound

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#100]
Currently, smart mute:

1. Removes Unread Count from tab title
2. Shows the "muted" icon on all conversations.

Both of these should be fixed, smart mute should not have any visual affect, should **not** mute notifications via whatsapp interface, but rather should only remove sound.

**Comment by liatzionimorad** [comment]
@ripper234  in the new implementation this is what it does. so I will wait for the formal version to close it
