### ISSUE TITLE
View Starred messages inline

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#14]
Show a small preview of the starred messages inline at the bottom of the conversation, along with a way to reach the message itself (e.g. up/down arrow that scrolls between the starred messages).

We need a global setting to turn this off/on via configuration (some people don't want to see the starred messages inline).

**Comment by liatzionimorad** [comment]
Dev:
questions: 
Q1:Where exactly should the preview be located and what should it look like? 
Q2:What should the settings include, can you give an example?

**Comment by ripper234** [comment]
Q1: It should be just above textbox where you enter the text messages in the chat. Please suggest 1-2 possible designs.
Q2: There is another on/off setting in another feature I edited today. And this setting as well - "View starred messages inline" (ON/OFF).

**Comment by liatzionimorad** [comment]
Team estimation
12hr - Frame with controls and msg preview in chat panel
5hr - Search method to fast scroll to between messages
1hr - Get starred messages
2hr - Add new option to Zen settings

) The initial result of the team is 20 hours.
2) In our experience, the team estimation error is 30%.
20 x 1.3 = 26
3.) Our insurance rate is 30%.
26 x 1.3 = 34
Full optimistic score out of 20 pessimistic out of 34 hours
