### ISSUE TITLE
Set auto read configuration should look different

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#143]
This is the way the setting looks today:
![image](https://user-images.githubusercontent.com/79567202/129733246-b10a1f21-9ee7-4c7e-8c45-e973f3ff86fb.png)

This is not clear.
We want the on\ off button to look like this:
ON :
![setting_on](https://user-images.githubusercontent.com/79567202/129874374-0d2729d1-a746-4833-8ad1-191fe729308b.png)

Off:
![setting_off](https://user-images.githubusercontent.com/79567202/129874411-e2711e97-9c46-436f-8cec-7c6d485048d5.png)

This was defined this way and never executed

**Also, rename "Auto-Mark hidden chats as Read"**

**Comment by ripper234** [comment]
Also rename "Auto-Mark hidden chats as Read"
