### ISSUE TITLE
Trello: Visible Separator 

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#147]
Currently the Trello Card in zen mode completely covers the entire screen.

However, there is still part of the screen that is "The Card", and the rest of it.

(Clicking outside of the card will close the card - the user needs to know where the card ends).

Can we have a fine/gentle border (maybe dashed?) to mark where the card ends?

![image](https://user-images.githubusercontent.com/172282/129929048-7125817b-36ab-4047-9f23-812b306e340f.png)

**Comment by liatzionimorad** [comment]
Will pass the team

**Comment by liatzionimorad** [comment]
done in 1.4.2.2
