### ISSUE TITLE
Clicking on selected option in snooze should be in a wider range of clicking

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#160]
We want snooze option to be chosen by clicking in the circle and in the very near area as well:
![image](https://user-images.githubusercontent.com/79567202/131445606-696b9c82-56a7-46d3-815d-89b8cafaa4fb.png)

**Comment by ripper234** [comment]
Let's get an estimate, I estimate this to be a super small fix.

**Comment by liatzionimorad** [comment]
Fixed in 1.4.2.4
