### ISSUE TITLE
Pulse / Snooze

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#19]
•	Pulse Mode
A channel is shown only once every X days.
•	(Too similar to Snooze?)
•	Snooze Channel
•	Channel is hidden until X days passed (X can be 1 hour, 1 day, 1 week, custom)
•	How to choose Custom?
•	Maybe have a +- sign, that changes from 1h, 1d, 1w, 1m, and a "Custom" button on the side)
•	Incoming messages to that chat do not cause it to show
•	You can view it in a separate Hidden channels list, and Show it (cancels Snooze)
•	Sending a message in a Hidden channel should Unhide it
•	This option should be configurable. In the config, you can make it so sending a message will keep it hidden.

**Comment by ripper234** [comment]
See also #42 for more spec that's similar to this. We might want to merge these features.

**Comment by liatzionimorad** [comment]
Questions from dev :
Q1:Where exactly should the preview be located and what should it look like? 
Q2:What should the settings include, can you give an example?
![image](https://user-images.githubusercontent.com/79567202/115993372-27dabe80-a5db-11eb-87b3-746c37abd70b.png)

![image](https://user-images.githubusercontent.com/79567202/115993381-30cb9000-a5db-11eb-978d-5992e11a0538.png)
![image](https://user-images.githubusercontent.com/79567202/115993393-375a0780-a5db-11eb-9c6c-c828f641d6f5.png)

Q3:Add the 'Unhide after sending message' switch to the main menu?

Q4: What does the custom period selection window look like?

Q5:  Where to place the 'Hidden channels' list?


My answers:
I think we should keep it simple so I would ask them what is easier to implement. I guess hide option for defined times with a additional menu *hide conversation will lead to > 1 day,  1 week , forever) ( answers for 1+2)
Q3Since we do not have a real hide I don't know if we want to unhide as a result of message sending
Q4: like a said above
Q5: Don't know

**Comment by ripper234** [comment]
Q3:

We want to unhide by default when sending a message. This should be the default behavior, and there should be a true/false setting in the main menu where you can disable this behavior.

Q4:
The graphics is incorrect. I asked for 4 options: 

1 hour
1 day
1 week
custom

Custom is a standard datetime picker that lets you pick a date + time for the duration of the mute.

Q5:
Hidden channels is not relevant right now, please ignore this.

**Comment by liatzionimorad** [comment]
Q1: Add the 'Unhide after sending message' switch to the main menu?
A1: Liat- still want unhide ?

**Comment by liatzionimorad** [comment]
Q2: What does the custom period selection window look like?
examples:
Format № 1
![image](https://user-images.githubusercontent.com/79567202/116253195-eda72380-a778-11eb-957e-713b222edcc9.png)
format 2
![image](https://user-images.githubusercontent.com/79567202/116253314-0adbf200-a779-11eb-94aa-b697d9e2e948.png)

**Comment by liatzionimorad** [comment]
Q7:What do you think of this format №2?
![image](https://user-images.githubusercontent.com/79567202/116255479-f39e0400-a77a-11eb-988d-e4b2925c94dd.png)

**Comment by liatzionimorad** [comment]
Q8: “Pulse mode” should hide the channel for X days, then show the channel for one day and then hide it again for X days and keep doing that as long as this feature is on, right?
A8: Liat- Yes

Q9: "Snooze Channel" works like a temporary hide, for a certain amount of time and works once, right?
“Snooze Channel” reminds me of a temporary mute.
A9: 
Liat Yes
Estimations:
5hr - pulse mode
5hr - snooze mode
5hr - unhide hidden channel after send message option

? - custom period for pulse popup
? - custom period for snooze popup
? - hidden channels list

**Comment by ripper234** [comment]
> A1: Liat- Default should be unhide after sending . within Zen menu add Settings sub menu to include this setting ( optional adding additional settings)

The new menu should include this setting, plus other configurations/settings for other features.

**Comment by liatzionimorad** [comment]
Final decisions regarding implementation of this feature :
 - upon pressing hide it should act like mute and suggest 3 options : hide for 8 hours, hide for a week hide forever.
 - Default behavior should be unhide after sending message to a hidden conversation.
 - Within Zen menu add  we want to add : Settings - a sub menu to include this setting ( optional adding additional settings) . It should state "unhide after sending message to a hidden conversation" ( default Yes).

**Comment by FrenkiBeggins** [comment]
Hello,Important comment.

The function will only work correctly if the conditions are met:
1.Chat must be open in target.Important condition: as long as we do not have access to high level api WA.
2.Chat must not be empty.Important condition: as long as we don't have access to high level api of WA.

**Comment by FrenkiBeggins** [comment]
You have opted out of the Custom option. Does this mean we are not adding a time picker dialog or do we need a different format?

**Comment by ripper234** [comment]
For the first iteration of this feature, no time picker.

**Comment by liatzionimorad** [comment]
team estimation :
5hr - time period choose dialog with '8 hours', '1 week', 'forever' options
3hr - adding toogle 'Unhide after sending message to a hidden conversation' option to settings
5hr - unhide after send message
5hr - snooze mode controller
1) The initial result of the team is 18 hours.
2) In our experience, the team estimation error is 30%.
18 x 1.3 = 24
3.) Our insurance rate is 30%.
24 x 1.3 = 31
Full optimistic score out of 18 pessimistic out of 31 hours

**Comment by liatzionimorad** [comment]
("החבא")In contact menu upon pressing hide:
"החבא את [converstaion name] למשך:"
8 שעות
שבוע
תמיד

at the bottom( like in mute):
right side for cancel is: בטל
for hiding is: החבא עכשיו

In the zen menu:
unhide after sending message to a hidden conversation" ( default Yes).

in Hebrew:
הראה צ'אט מוחבא לאחר ששלחת הודעה לצ'אט זה ( default yes-> כן)

**Comment by liatzionimorad** [comment]
last estimation:
Task № 30.
1) Initial estimate 18 hours
the team is wrong 30% of the time.
18 x 1.3 = 24
2) Our safety stock ratio is 30%
24 x 1.3 = 31
3) Optimistic estimate 24 hour,pessimistic assessment 31 hours.
