### ISSUE TITLE
Visibility Schedule (for a chat)

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#196]
יSelective show
Show the group only
Days selector
Hours selector

Something like this:
![image](https://user-images.githubusercontent.com/79567202/148180246-f4e7e208-e9d4-46a3-8be9-bec1a3fe48b0.png)

* should add the ability to see all contacts set like this, return to default? Change?

**Comment by ripper234** [comment]
Three options

1. All the time
2. Weekdays (ask the user what time range every day)
3. Custom

**Comment by ripper234** [comment]
![image](https://user-images.githubusercontent.com/172282/148194826-10c80fa5-09d7-4e89-a24a-5ebfd103a412.png)


(All the Time instead of Every Day)

**Comment by ripper234** [comment]
And "Visibility Schedule" instead of "Allow notifications".

**Comment by ripper234** [comment]
Option 2

![image](https://user-images.githubusercontent.com/172282/148195094-7c9fae22-246b-4632-babf-441057fefe9d.png)

A) For now, Weekdays are Sundays-Thursday
B) This should be reflected in both the order of days, and the reminder text

You won't *see this group* on Friday or Saturday.

**Comment by ripper234** [comment]
Option C

(Should start on Sunday)

![image](https://user-images.githubusercontent.com/172282/148195388-d4b090e8-4d4e-438c-900f-8b6faa01bf74.png)

**Comment by ripper234** [comment]
In all three options, there should be text above, that explains the feature:

You'll only see this chat in the days/hours you choose.
(you can always access it via archived groups or Show Hidden Groups)

**Comment by liatzionimorad** [comment]
1. Dev :. What if the chat is hidden and the visibility schedule is set. What logic should we use?
Suggestion: For hidden chats, there will be no item with setting a schedule at all. When the schedule is set and we hide the chat in the dialog with the choice of hiding options, write "This action will cancel the visibility schedule"

@ripper234 - this makes sense to me please approve

2. Do we need to somehow distinguish between manually hidden chats and scheduled chats?
@ripper234  - I think not at this  stage please approve

 What should happen to the chat hiding schedule when we click "Show Chat"?

@ripper234  To my view should show all.

**Comment by liatzionimorad** [comment]
Hebrew translation:
There is also a request from the developer. Please provide correct Hebrew translations of the following phrases:
- You'll only see this chat in the days/hours you choose. (you can always access it via archived groups or Show Hidden Groups)
" אתה  תראה את הצ'ט הזה רק בימים/שעות לבחירתך. ( יכול תמיד לגשת לצ'ט דרך הארכיון או רשימת הצ'טים המוסתרים)"
- Visibility Schedule ->" זמני הצגת הצ'ט" )
- All the time -  תמיד
- Weekdays - ימי עבודה
- Custom - מותאם
-Sunday - ראשון 
- Monday - שני
- Tuesday - שלישי
- Wednesday- רביעי
- Thursday - חמישי
- Friday - שישי
- Saturday- שבת
- Sunday
[12:28, 11.2.2022] ליאת ציוני מורד: ok will do all on Sunday

**Comment by ripper234** [comment]
1. Good suggestion, agreed.

2. No need right now.

3. Hiding a chat cancels the visibility schedule. So, when a user clicks "Show Chat", it returns to "Show All". Any information about previous visibility schedules is not saved.


Translations:

4. 
"אתה תראה את הצ'ט הזה רק בימים/שעות לבחירתך. (ניתן תמיד לגשת לצ'ט דרך הארכיון או רשימת הצ'טים המוסתרים)"

5. Custom  - נראה לי ש "מותאם אישית" יותר מתאים, לא?
