### ISSUE TITLE
Visiblity Schedule should only Save preferences when someone clicks OK

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#225]
When someone clicks "X" to close the config window for Vis Schedule, instead of clicking OK:

1. If the user didn't make any changes, the window should close silently (like today).
2. If the user made any changes, then a popup should pop up "Discard your changes?"

Motivation - X should not save the changes. The user should have a way to quit without saving changes.

TODO - specify this feature further.

**Comment by liatzionimorad** [comment]
@IvanTotti  fixed in 21 please check

**Comment by IvanTotti** [comment]
@liatzionimorad  Preferences are saved only after the user clicks OK, but the mentioned point number **2. If the user made any changes, then a popup should pop up "Discard your changes?"** is not appearing

**Comment by IvanTotti** [comment]
Tested, Everything is working fine.
