### ISSUE TITLE
Add a pinned icon next to the chat

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#232]
![image](https://user-images.githubusercontent.com/79567202/174760717-b095e1c5-3e4f-4e83-9a4e-22a93ac75562.png)
when in Hebrew the icon will be aligned to the right
when in English to the left

**Comment by CptFatBu11et** [comment]
@liatzionimorad

estimate 2-3 h

**Comment by liatzionimorad** [comment]
@CptFatBu11et approved
