### ISSUE TITLE
Change default state of pinned chats to on+ pop up upon first appearance

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#233]
![image](https://user-images.githubusercontent.com/79567202/174761363-d876a97b-620f-4138-908e-f80ce18a9971.png)

The version should be with pineed status chats is on
Upon first indication a pop up should appear stating "Show pinned chat status is on! You can change the mode in Zen Mode menu"
In Hebrew "הצגת מצב צ'אטים מוצמדים פעילה, לשינוי יש לגשת לתפריט זן"

**Comment by CptFatBu11et** [comment]
@liatzionimorad 

estimate 5-7 h
