### ISSUE TITLE
Different mouse icon for - Offline mode icon

### ISSUE THREAD

**Issue by IvanTotti** [zen-mode/Whatsapp-Zen-Mode#234]
There is a ****different type of mouse icon** for Offline mode** icon and for example for Zen Mode icon. When the user is trying to click on ZEN MODE icon the mouse icon is in shape of a hand with a finger pointing on the Zen Mode icon and its the same for all click-able buttons in whatsapp enviroment . But **for Offline Mode the mouse icon is not a hand but a basic arrow icon. This should be changed to the hand mouse icon so we have the same mouse icon for all click-able areas.**

![basicicon](https://user-images.githubusercontent.com/105730382/174770745-823a54d0-72b8-42ba-9968-ba1d638b943b.jpg)

![handicon](https://user-images.githubusercontent.com/105730382/174770824-8893b739-78a0-46b2-88c6-58e406dc9fb6.jpg)

**Comment by CptFatBu11et** [comment]
@liatzionimorad 

estimate 10-15 minutes

**Comment by liatzionimorad** [comment]
@CptFatBu11et  approved

**Comment by IvanTotti** [comment]
Tested, Everything is working fine.
