### ISSUE TITLE
We would like to add an icon to hide chat

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#235]
![image](https://user-images.githubusercontent.com/79567202/174775615-245cf232-2761-49be-a090-bd34dde919e3.png)

Please suggest an icon

**Comment by CptFatBu11et** [comment]
@liatzionimorad 

estimate <1 h

**Comment by liatzionimorad** [comment]
@CptFatBu11et approved

**Comment by IvanTotti** [comment]
Tested, Everything is working fine.
