### ISSUE TITLE
Add a Readme.md file and possibly CONTRIBUTING guide

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#25]
Readme.md should contain basic instructions on what this is, and point to chrome store & contributing.

CONTIRBUTING should be aimed at people who want to contribute to the project in any way (e.g. writing code, submitting issues & feature requests, etc.)

https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

One thing I'd like to see in a contributing guide is an explanation of the labels, if we use a non-standard label structure. Right now I see we have "Feature Request" & "Feature Thoughts" labels. Thoughts is non-standard.

What's the difference between request & thoughts in this context?

**Comment by ripper234** [comment]
Also, @liatzionimorad  - do you get notified when new issues are created?

I've created #26 to test this.

**Comment by ripper234** [comment]
I might be wrong and Feature Ideas is standard?
It's been a long time since I githubbed :)

**Comment by liatzionimorad** [comment]
Didn't know there is a standard :-)  we can decide on it .
