### ISSUE TITLE
Fix hide functionality

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#33]
The target is to hide a conversation completely. (Un like what we did in 1.3.0 - Current solution : display user avatar and name but not last line sent or message counter).
This was done sue to difficulties in implementation ( full hiding of a contact:)
Ability to hide a conversation does not work as intended. Keeps blank space in place of a hidden contact.
This happens because WA Web has a complicated proprietary internal system of Contact List management and layout; very different from common approaches to HTML.

**Comment by liatzionimorad** [comment]
After further investigation we decided to keep implementation as is :Avatar and contact name only when  contact is hidden. Currently un operative in version. Need to re activate.

**Comment by ripper234** [comment]
The title is generic, let's rename

**Comment by liatzionimorad** [comment]
We opened #48 for this issue
