### ISSUE TITLE
Have a Zen Morning

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#41]
Motivation
----------
I would like to check my messages with my partner before I dive into the chaos of incoming messages every morning.

I would like to always, automaticaly, start my morning in Zen Mode on a predefined conversation. I would like to preconfigure one specific conversation (via right clicking it, see ahead) - and then have the extension automatically each morning at 4AM to turn ON, and focus on this conversation. This happens regardless if Zen Mode was OFF before, or was ON on another conversation (or maybe on this one).

How to select the "One special conversation"?
---------------------------------------------
Add to the Conversation Menu (currently contains only "Hide") a new action "Zen Morning". When clicking it a dialog appears that explains this, with a Yes/No button. Dialog text:

"Wake up every morning with Zen Mode focused on this conversation. Note, this will disable any previously selected Zen Morning conversations"

In Hebrew :
"הער אותי כל בוקר במצב זן על השיחה הנוכחית. לתשומת ליבך  בחירה בכן תבטל כל הגדרה קודמת של בוקר זן "
button : "כן/לא"

**Comment by ripper234** [comment]
Something to watch for: I'm concerned that if we automatically switch Zen Mode on and move it to the Special Conversation, and then afterwards in the night this contact sends you a message - your Whatsapp Web might accidentally mark this conversation as read. If your computer is open with browser focus on whatsapp web, I suspect this might happen sometimes.

If the computer is asleep / on screensaver, I believe this won't happen.

And BTW the feature should work / be tested both for these cases:

1. Brower window is closed.
2. Brower window is opened, is not in focus at night
3. Brower window is open and in focus at night

The desired result is that this conversation won't accidentally be marked as read.

Also note - the Zen Time of 4AM noted above - it's ok to go with a predefined number (should match the user's timezone). In later iterations of these feature we'd like an option to configure this time.

**Comment by liatzionimorad** [comment]
from dev :You want the 'Zen Morning' to activate only after the user has started using WA, in the morning respectively.
Did I understand you correctly?

My answer: 
1.the scenario is user started working with zen mode.
2. He defines Zen morning
3. This status should apply on all browser status ( if I closed browser at night and reopened in the morning ) this should apply as well

**Comment by ripper234** [comment]
Yes, Zen Morning is only applicable when using WA and should be persistent across browser sessions.

**Comment by liatzionimorad** [comment]
Dev:
Q2: In fact, 'Zen Morning' should open the previously selected channel every morning when the user has started working in WA. This is how I understand the task now.
A2:
Liat - yes.

Q3: "persistent across browser sessions", you want Zen Morning to store the selected chat setting for each account?
I don't quite understand your clarification.
A3: 
Liat - I think the intention was - if I close browser and reopen it definition remains as is

**Comment by FrenkiBeggins** [comment]
Hello,I will add information.
Estimations:

4hr - yes/no popup
7hr - detect real user activity
1hr - redirect user to chat by deep wa URL
5hr - tests

The initial result of the team  - 17 hours
2) In our experience, the team has an estimate error of 30%.
17 x 1.3 = 22
3.) Our insurance rate is 30%.
22 x 1.3 = 29
Full optimistic assessment from 17 pessimistic from 29 hours

**Comment by FrenkiBeggins** [comment]
Do you want to add only one contact to this mode? Do you need the ability to add multiple people to this mode?

**Comment by ripper234** [comment]
Only one contact.

From the spec: (this text is shown to the user)

"Wake up every morning with Zen Mode focused on this conversation. Note, this will disable any previously selected Zen Morning conversations"

**Comment by liatzionimorad** [comment]
Planned to be delivered on the 18/5

**Comment by liatzionimorad** [comment]
1.4.0.3
