### ISSUE TITLE
Unhide all stops working

### ISSUE THREAD

**Issue by nikshirobokov** [zen-mode/Whatsapp-Zen-Mode#43]
After F5, when scrolling down, I find old hidden chats. Unhide all also does not work for them. For old hidden chats, to which you need to scroll, you have to press Hide first, then unhide, then they start working

**Comment by liatzionimorad** [comment]
Refresh issue- state is not maintained after refresh of hidden

**Comment by nikshirobokov** [comment]
![image](https://user-images.githubusercontent.com/40653060/114860649-13920700-9e0e-11eb-9cf3-dcf53d2cbd5a.jpeg)

**Comment by ripper234** [comment]
Fixed
