### ISSUE TITLE
Zen mode timer +hidden

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#45]
I also have a suggestion for you.
During testing I left some chats hidden and forget about it. 

I'm not sure whether chats should be hidden after WA refreshing or after computer reboot.

My idea is to add timer to Zen mode. 
Like Sleep mode on mobile devices.
For example, I come to work and set time for 8 hours(or till 18:00) and after that time all chats become unhidden again.

**Comment by ripper234** [comment]
This is sorta like #42 , someday will be implemented by an evolution of that. Closing for now.
