### ISSUE TITLE
Full Screen for Trello cards

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#49]
**Note** - this is the first branching out of Zen Mode from Whatsapp into other platforms.

As a Trello user, whenever I open a Trello card, I would like the background to be "gone" in a nice way.

Currently, when I open [this card](https://trello.com/c/20GdAhAQ/3-trello-development-fog-creek-software) for example, I get

![image](https://user-images.githubusercontent.com/172282/116524192-c74fc800-a8df-11eb-8ba0-13f5801d588f.png)

I would like the ZM extension to do a few modifications on that. Please deliver the feature incrementally.

**Phase 1** - fill the background with the same gray color that is the background for the card.

This phase also adds the Zen Mode icon into Trello. Default is ON (opposed to whatsapp's OFF default). Clicking this button persistently toggles the state from ON/OFF. When OFF, the extension doesn't do anything.

![image](https://user-images.githubusercontent.com/172282/116525589-57dad800-a8e1-11eb-8b9f-246f082e4f46.png)

Phase 2 - Offer the user a choice (via Zen Mode Menu --> "Background") between gray, white & black
Phase 3 - Offer the user a choice between these 3 colrors (ZM Menu --> Background --> Color --> White), and a Blur (ZM Menu --> Background --> Blur). The Blur option is a 50% gaussian blur of the background.

Phase 4 - the user can choose to use an image (that only we provide. he cannot upload an image). ZM Menu --> Background --> Image

What image do we use?

I'm thinking of something in the spirit of Zen Mode logo. It needs to be full screen / high resolution. The goal is peace and calm and almost zero distracting details in the image. We would like to get 3 options for a suitable image, and then choose what goes into the extension. The extension will only support one image, not 3 - the 3 options are sent to Zen Mode management to select, during the dev process.

*Note* - these sections in the ZM Menu should only be available while on Trello.com. They should not appear in Whatsapp Web. The ZM Menu should ONLY contain the options above, when visiting Trello.

**Comment by liatzionimorad** [comment]
Will publish and update

**Comment by liatzionimorad** [comment]
Done 1,4,2,4
