### ISSUE TITLE
Hide related bugs:

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#53]
Unhide inconsistent behavior :
Occasionally seeing last text and counter of hidden contact- whereas Zen menu considers the group as hidden .
another symptom : hidden group sometime appears with this indication upon incoming message :

![image](https://user-images.githubusercontent.com/79567202/116809152-5e698980-ab45-11eb-9b3f-0fee663f7bbe.png)

**Comment by FrenkiBeggins** [comment]
another symptom :
 Do you mean that sometimes the last post from that group appears in place of the name of the hidden group?

**Comment by liatzionimorad** [comment]
Hi @FrenkiBeggins , 
This issue is related to the counter of the messages that may appear as a counter or as a grey circle indication like shown in the image.
 
Another issue is that the hide just stops hiding completely ( this is not the case here)

**Comment by FrenkiBeggins** [comment]
Hello.
Now a gray circle appears when a hidden contact sends you the first message.
What you need to do:
1. Remove the gray circle.
2. fix the gray circle. The gray circle will appear whenever there is a new message.

**Comment by liatzionimorad** [comment]
Hi,
For now we hold the fixing of this bug until final estimation on #48 
If we need to fix it in the future no grey circle should appear. ever.

**Comment by liatzionimorad** [comment]
Implementation changed
