### ISSUE TITLE
Hide issues

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#55]
A conversation that should be hidden - starts showing data 
The  menu indicates the mode is considered "hidden" but we see it is not
![image](https://user-images.githubusercontent.com/79567202/117108673-31f37e80-ad8c-11eb-9f50-fe27097fdd83.png)
![image](https://user-images.githubusercontent.com/79567202/117108729-4899d580-ad8c-11eb-965c-6f1b01961773.png)

**Comment by liatzionimorad** [comment]
#53

**Comment by liatzionimorad** [comment]
We are holding handling in hide issues until final estimation on #48 that may change the code entirely

**Comment by ripper234** [comment]
The title "Hide Issues" is generic.
Maybe rename or split to separate bugs? (if this is multiple issues)

**Comment by liatzionimorad** [comment]
Will split it- after we realize if still valid.
