### ISSUE TITLE
Mute notification sounds of hidden conversations. 

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#56]
No sound from hidden conversations should be played while hidden ( even if not as Zen mode)
When conversation is un hidden - notifications should not be muted

**Comment by ripper234** [comment]
Pending on hide feature

**Comment by ripper234** [comment]
We probablly want this around v1.5.0-1.6.0

**Comment by liatzionimorad** [comment]
works like this in 1.4.0.11
