### ISSUE TITLE
Icon stating contact selected for Zen Morning

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#60]
Draw a small sun icon next to the contact selected as "Zen Morning". It should always have the sun, as long as ZM is active on them.

When a different conversation is chosen the Icon should be active on the newly selected one. ( since only one Zen Morning contact can be set)
![image](https://user-images.githubusercontent.com/79567202/119261435-1be51b00-bbe0-11eb-99a8-1a4db7f3016c.png)

**Comment by FrenkiBeggins** [comment]
The initial result of the team is 3 hours.
In our experience, the team estimation error is 30%.
3 x 1.3 = 4
3.) Our insurance rate is 30%.
4 x 1.3 = 5
Full optimistic score out of 3 pessimistic out of 5 hours

**Comment by liatzionimorad** [comment]
done 1.4.0.3
