### ISSUE TITLE
Unhide contact should be done using a contact menu to right click

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#70]
Un hide of specific contact is shown via right click. like this: 
![image](https://user-images.githubusercontent.com/79567202/119779332-3b768f00-bed1-11eb-91b8-0dad96e79fe5.png)

should be implemented by contact menu like in archive

![Inkedscreen2_LI](https://user-images.githubusercontent.com/79567202/119780560-a2e10e80-bed2-11eb-8c8a-dea589b1805d.jpg)

**Comment by FrenkiBeggins** [comment]
Task № 60 in  task list
Un hide of specific contact is shown via right click. like this:
![102 (1)](https://user-images.githubusercontent.com/80031884/120885990-5e512380-c5f4-11eb-9169-1f8242493cf5.png)



should be implemented by contact menu like in archive


60.A. Finding a method to call right-click menu creation using the WW api
OR
60.B. Render copy existing context menu via custom class. Needs logic developing for each:
![pasted image 0](https://user-images.githubusercontent.com/80031884/120886014-6f9a3000-c5f4-11eb-924c-c38a0711ace5.png)

60.B.1: Unhide chat button
60.B.2: Mark as read
60.B.3: Delete chat button
60.B.4: Custom logic for rendering right-angle arrow
60.B.5 Custom logic for rendering ctx menu
Estimates
60.A - 4hr
The initial result of the team is 4 hours.
2) In our experience, the team's estimate error is 30%.
4 x 1.3 = 5
3.) Our insurance rate is 30%.
5 x 1.3 = 7
Full optimistic estimate out of 4 pessimistic out of 7 hours.
OR
60.B
60.B.1 - 1h
60.B.2 - 4h
60.B.3 - 5h
60.B.4 - 3h
60.B.4 - 7h

The initial result of the team is 20 hours.
2) In our experience, the team's estimate error is 30%.
20 x 1.3 = 26
3.) Our insurance rate is 30%.
26 x 1.3 = 34
Full optimistic estimate out of 20 pessimistic out of 34 hours.

**Comment by ripper234** [comment]
We do not need 60.B.2 and 60.B.3.

Only 60.B.1 and 60.B.4-60.B.5.

Can you restimate?

@FrenkiBeggins

**Comment by FrenkiBeggins** [comment]
Hi. We will reevaluate.
