### ISSUE TITLE
When looking for a hidden conversation the indication is archived 

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#81]
https://www.loom.com/share/804730bc596b4ada92e728f5a22349f9

**Comment by FrenkiBeggins** [comment]
Task 55
55.1 The initial result of the team is   2-3 
2) In our experience, the team's estimate error is 30%.
2 x 1.3 = 3
3.) Our insurance rate is 30%.
3 x 1.3 = 4
Full optimistic estimate out of 2 pessimistic out of 4 hours.

55.2 -? (will become known after 55.1)

Fix hidden chat finds in chat search.
 
55.1 Let's explore if it is possible to implement using WW api

55.2 If 55.2 is possible, evaluate the implementation.

**Comment by liatzionimorad** [comment]
@FrenkiBeggins when I am looking for a hidden chat it is OK that I will see it. The only thing is that it should state "hidden" instead "archived". No other different behavior is required.
Is your evaluation referring to this?

**Comment by ripper234** [comment]
55.4 - 4hr
55.5 - 2hr
55.6 - 1-2hr
55.4 Add method for replacing Archive icon to “Hidden” in chat HTML element
55.5 Add method to scroll observer
55.6 Add “Hidden” span to Chat HTML element
The initial result of the team is 7 hours.
2) In our experience, the team's estimate error is 30%.
7 x 1.3 = 9
3.) Our insurance rate is 30%.
9 x 1.3 = 13

**Comment by liatzionimorad** [comment]
Liat : approved
