### ISSUE TITLE
Smart mute stops working

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#82]
The system is in smart mute on
every things works fine
suddenly notifications are heard( without changing the smart mute mode)

**Comment by liatzionimorad** [comment]
https://www.loom.com/share/fd926d5d9e474007a64ac26e11f3dd20

**Comment by liatzionimorad** [comment]
@FUZIK 
![image](https://user-images.githubusercontent.com/79567202/122082315-946a8080-ce08-11eb-9b40-28dff3f6b404.png)
No way to stop the mute...

**Comment by liatzionimorad** [comment]
https://www.loom.com/share/32b29a097863467c936549229efc2554

**Comment by FUZIK** [comment]
@nikshirobokov Обрати внимание на этот метод. Он вызывается в интервале каждую десятую секунды.
https://github.com/zen-mode/Whatsapp-Zen-Mode/blob/6b1e0aaed0f95e7ef58b4d17c408915f5b979002/src/features/extension-can/display-zen-mode-ui/attach-zen-mode-ui.ts#L76
