### ISSUE TITLE
inconsistent behavior of Zen Morning

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#87]
There are different occasions in which Zen Morning is not operating as it should:
1. Becomes active not on selected contact 
2. A more detailed scenario ( may be same issue):
 *  Open WAW - Zen morning became active on selected contact
 *  Set Zen Mode on and off on this contact
 * Updated browser
 * Re open browser and WAW
 * went to a conversation ->Zen Mode suddenly activated (not a contact defined as Zen morning)

**Comment by liatzionimorad** [comment]
Dev :
Hello.
Task 66 in tasklist
The initial result of the team is 3 hours.
2) In our experience, the team's estimate error is 30%.
3 x 1.3 = 4
3.) Our insurance rate is 30%.
4 x 1.3 = 5
Full optimistic estimate out of3 pessimistic out of 5 hours.

**Comment by liatzionimorad** [comment]
Liat - This was approved

**Comment by ripper234** [comment]
+ when new version is installed.
