### ISSUE TITLE
Zen Menu appears in the wrong place

### ISSUE THREAD

**Issue by ripper234** [zen-mode/Whatsapp-Zen-Mode#88]

**Comment by ripper234** [comment]
https://www.loom.com/share/1af1d7e706124c03ab3079fe4d42bf9f?sharedAppSource=personal_library

**Comment by ripper234** [comment]
@liatzionimorad should test how it is in Hebrew / RTL

**Comment by ripper234** [comment]
Note: this happens for some users (me & Liat) whether Zen Mode is on or off.

For other users it doesn't happen.

**Comment by nikshirobokov** [comment]
> Maybe related to screen resolution? I'm working in 1920x1200.

Of course. That's reason. This issue should be correcting via #96

**Comment by liatzionimorad** [comment]
1.4.1.0
