### ISSUE TITLE
 Smart Mute - Mute everything except voice messages you play

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#9]
New button in the Zen Menu titled Smart Mute + icon of muted speaker (Button has two states: mute & unmute)

**Comment by liatzionimorad** [comment]
team estimation :
2hr - Inspect whether it is possible to implement using the high-level API.
1) The initial result of the team is 2 hours.
2) In our experience, the team estimation error is 30%.
2 x 1.3 = 3
3.) Our insurance rate is 30%.
3 x 1.3 = 4
Full optimistic score out of 2 pessimistic out of 4 hours

**Comment by FrenkiBeggins** [comment]
1.Should mute all contacts by the “Smart Mute” button clicked? Or the “Smart Mute” button used to toggle mode: 
On: Auto mute all sounds by audio playing
Off: Not happens

2.'Smart Mute' toggle button work for the target chat you are in or for all chats?

**Comment by ripper234** [comment]
1.
As per the title:

When ON - Mute everything except voice messages you play
When OFF - Don't mute anything

2.
It works for all chats

**Comment by liatzionimorad** [comment]
@FrenkiBeggins  please notice:
In Zen menu 
English : Smart mute on\ Smart mute off.
Hebrew : הפעל השתקה חכמה/ כבה השתפה חכמה

To clarify to user we would like hover text upon menu command :

English :Mutes all sounds except audio and video messages you play
Hebrew :השתק את כל הצלילים מלבד הודעות קוליות ווידאו שאתה מנגן

**Comment by liatzionimorad** [comment]
Done in 1.4.0.10
