### ISSUE TITLE
Translate to Hebrew - Hidden chats -> צ'אטים מוחבאים 

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#91]
Upon Hebrew Chrom version the title should be in Hebrew:
![image](https://user-images.githubusercontent.com/79567202/121864852-0017f500-cd06-11eb-82ad-45eb049882a7.png)

"שיחות מוחבאות"

**Comment by liatzionimorad** [comment]
@ripper234  we need to decide :
שיחות מוחבאות או כמו ווטסאפ צ'אטים מוחבאים
אם הולכים על צ'אט אנחנו צריכים לשנות בכל התפריטים

**Comment by ripper234** [comment]
הולכים על צ'טים

**Comment by ripper234** [comment]
או צ'אטים

**Comment by liatzionimorad** [comment]
Additional translation changes required:
![image](https://user-images.githubusercontent.com/79567202/122220803-5aa58280-ceb9-11eb-9a58-81fab9268155.png)


Instead :הראה שיחות מוחבאות  should be  : הראה צ'אטים מוחבאים
Instead : הראה רשימת שיחות מוחבאות should be : הראה רשימת צ'אטים מוחבאים

**Comment by liatzionimorad** [comment]
Task №71 in task list
The initial result of the team is 1 hours
2) In our experience, the team's estimate error is 30%.
1 x 1.3 = 2
3.) Our insurance rate is 30%.
2 x 1.3 = 3
Full optimistic estimate out of 1 pessimistic out of 3 hours
