### ISSUE TITLE
Changes in menu and zen mode activation

### ISSUE THREAD

**Issue by liatzionimorad** [zen-mode/Whatsapp-Zen-Mode#96]
all changes are detailed here:
https://docs.google.com/document/d/1Ut8M56YDg74ySAvnYy-RwuXKVHtORZa-MXuqGyuaj0Q/edit?usp=sharing

**Comment by nikshirobokov** [comment]
@liatzionimorad I think isn't a bug. May be enhancement?

**Comment by liatzionimorad** [comment]
@nikshirobokov  I agree.
